[package]

name = "external"
version = "0.0.1"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]

[dependencies.bitflags]
git = "https://github.com/rust-lang/bitflags"

[dependencies.frame_stack]
path = "../frame_stack"